# This is a pipeline TEMPLATE for deploying Logic Apps across dev, test, qa and prod

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r) # build numbering format
resources:
  repositories:
    - repository: commontemplates # do not change this name to something else, the referenced pipeline uses this internally
      type: git # Azure DevOps repo
      name: Integration Delivery/Common # name needs to be hardcoded, cannot use variables here
      ref: master

variables:
- group: common-env # Links in values from this variable group, expected to contain: serviceconnection, az-location, subscription-dev, subscription-test, subscription-qa, subscription-prod

# Resource groups
- name: resourcegroup-dev 
  value: '<<RG-DEV-NAME>>'
- name: resourcegroup-test 
  value: '<<RG-TEST-NAME>>'
- name: resourcegroup-qa 
  value: '<<RG-QA-NAME>>'
- name: resourcegroup-prod 
  value: '<<RG-PROD-NAME>>'

# Properties for naming and grouping  
- name: businessobject
  value: '<<BUSINESSOBJECT-NAME>>'
- name: logicappname
  value: '<<LOGICAPP-NAME>>' # Requirement - this should be the same with the same case for folder, template file, and prefix for web app --> ie 'INT-TrainComposition-I-E-MapRPSToVognOpptak' , for WebAppName a suffix is added by the script, ie '-dev-fa'

trigger:
  branches:
    include:
    - '*'
  paths:
    include: # Include needs to be hardcoded, cannot use variables or trigger wont trigger
    - LogicApps/<<LOGICAPP-NAME>>/*

pool:
  vmImage: 'ubuntu-latest'    

stages:
- template: PipelineTemplates/logicapps-shared.pipeline.yml@commontemplates  # Template reference